# Netlify configuration
[build]
  publish = "website"
  command = ""
  functions = "netlify/functions"

# Simple SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build.environment]
  NODE_VERSION = "18"

# Context settings
[context.production]
  command = ""
  publish = "website"

[context.deploy-preview]
  command = ""
  publish = "website"

[context.branch-deploy]
  command = ""
  publish = "website"
